modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "wondertrade"
version = "${version}"
displayName = "WonderTrade"
authors = "Zonary123"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.wondertrade]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wondertrade]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wondertrade]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.5.0,)"
ordering = "AFTER"
side = "BOTH"