modLoader = "javafml"
loaderVersion = "[2,)"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${author}"
description = '''${mod_description}'''
logoFile = "${mod_icon}"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.90,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "cobblemon"
type = "required"
versionRange = "[1.8.0,)"
ordering = "AFTER"
side = "BOTH"
